stephencelis/SQLite.swift

- SQLite Common/Query.swift
Hello!
It can be helpful to build up the setters for a query dynamically. If Swift supported splatting, then the existing `insert` could be used (e.g. `insert(*[name <- "Alice", email <- "alice@mac.com"])`), but it doesn't (https://devforums.apple.com/message/970958).
This diff lets the columns be built up dynamically. For example:
var values = [name <- "Alice"]
if shouldSetEmail {
values.append(email <- "alice@mac.com")
}
if let insertedID = users.insert(values) {
...
}
If you think this is a good idea, `update` should also be changed to allow an array of setters.
> Allow values to insert to be passed as array of setters

- SQLite Tests/ValueTests.swift
- SQLite.xcodeproj/project.pbxproj
- SQLite/Value.swift
Missed a Foundation dependency that is automatically bridged: `String(format:)`. Some reason it still works without the import.
Added toHex() method to Blob and replaced `String(format:)` in Blob.description with it. Added a test for it.
> Replace Foundation String format with Swift version

- SQLite.swift.podspec
The **require_relative** is not working, changed to **require** and setting the $LOAD_PATH previously
> Solve [!] Invalid `SQLite.swift.podspec` file: cannot infer basepath

- .gitignore
This prevents an issue where any git repo that included SQLite.swift as a submodule using Carthage would be marked dirty. This happened because SQLite.swift builds itself using Carthage, and the resulting build artefacts are untracked by git resulting in the submodule being marked dirty. We can avoid that by just ignoring the _Carthage_ directory.
> Ignore the Carthage directory

- Documentation/Index.md
Just some suggested changes. I was hitting some `database is locked` errors myself and it took a while to figure out what was up based on the current documentation. Figured I'd add some extra information about `busyTimeout` and `busyHandler` here.
> Add threading info to documentation

- README.md
- SQLite.playground/Contents.swift
- Source/Core/Connection.swift
- Source/Core/Statement.swift
- Source/Typed/Query.swift
- Tests/ConnectionTests.swift
- Tests/FTS4Tests.swift
- Tests/QueryTests.swift
Reopened against master, replacing https://github.com/stephencelis/SQLite.swift/pull/221
Propagates up errors by replacing a `try!` in the init method for Statements with try and adding the necessary acknowledgements of this throughout the code. See issue https://github.com/stephencelis/SQLite.swift/issues/220
> propagate errors in Statement initialization

- Source/Typed/Query.swift
- Tests/QueryTests.swift
The same thing exists for `group` so I figured not having one for `order` might have been an oversight.
Copy/pasted the documentation from above (just like `group`).
Tests still pass.
:smile:
> Add order method to query that takes an array arg

- Documentation/Index.md
Copied the Carthage install from the readme for people who end up here directly.  _Not terribly DRY, but short of trimming the front page or linking back to it, it's arguably an improvement._
> Add Carthage install info to main documentation

- Source/Cipher/Cipher.swift
- Tests/CipherTests.swift
Adds key and rekey methods that accept a key of type NSData.
This allows the database to be easily keyed with a key generated by
Security.framework:
```swift
let keyData = NSMutableData(length: 64)!
SecRandomCopyBytes(kSecRandomDefault, 64,
UnsafeMutablePointer<UInt8>(keyData.mutableBytes))
db.key(Blob(bytes: keyData.bytes, length: keyData.length))
```
> SQLiteCipher NSData key support

- Documentation/Index.md
- Documentation/Planning.md
- README.md
_Note: This PR only affects document files. It does NOT change any code._
To try and help out (after checking with @stephencelis), I've been going through the issues to pull out enhancement requests and also to propose a roadmap for priorities. This PR is my first stab at this. If accepted, I'll close the referenced issues.
Why? My thesis is that the less open issues the better, for the following reasons:
* many projects have a roadmap and this can be a useful guide for people and cut down on repeat questions
* it's nice to see if a feature request has already been made and find a link to the history (via a closed issue, in this case)
* if there are just a few issues open, it's easier to look for things to help, or known problems
* I often judge a project's quality by how many issues are …
> Start moving issues into tracking document, minor docs example tweak

- Documentation/Index.md
- README.md
> Lock installation to tag

- Documentation/Index.md
- README.md
- SQLite.swift.podspec
- SQLite.xcodeproj/project.pbxproj
- SQLite/Core/Connection.swift
- SQLite/Core/SQLite-Bridging.h
- SQLite/Core/SQLite-Bridging.m
- SQLite/Core/Statement.swift
- SQLite/Helpers.swift
- SQLite/Info.plist
- SQLite/SQLite.h
- SQLite3/module.modulemap
- podstuff/module.modulemap
* Revert including sqlite3 as an Xcode module to fix #324 and instead use the sqlite.h file and linked library setting
* Add back some of the CocoaPod tweaks from prior to 0.9.0
* Add `tvos` to the podspec for #325. Add `OSX` while we're there.
* Possibly fix #326, though it's a bit hard to say without more info what is actually going on there.
* update docs to be 0.9.2
* add some pretty buttons to the top of the readme - (the "platform iOS" should become ios/tvos/osx once this is pushed to CocoaPods)
> 0.9.2 candidate. Hopefully fixes: #324, #325, #326

- SQLite.xcodeproj/project.pbxproj
Reminder: will need to tag this update for Carthage to be happy.
> Fixes #335 - allow OSX 10.9 and above instead of 10.11

- Documentation/Index.md
Based on the recent #332 issue, and earlier similar questions, I've added this note to the documentation. Linking to SO is a short-term measure, but if it stops new issues being opened, then everyone wins imnsho.
> Added links to SO articles with more iOS info

- SQLite.xcodeproj/project.pbxproj
SQLite fails to build with Carthage on Macs with case sensitive file system.  The build fails with:
The following build commands failed:
ProcessInfoPlistFile /Users/mkistler/Library/Developer/Xcode/DerivedData/SQLite-fciegensodowgvfsgoskujfmqkpa/Build/Products/Release/SQLite.framework/Versions/A/Resources/Info.plist SQlite/Info.plist
(1 failure)
error: could not read data from '/Users/mkistler/Projects/myproj/Carthage/Checkouts/SQLite.swift/SQlite/Info.plist': The file “Info.plist” couldn’t be opened because there is no such file.
A shell task failed with exit code 65:
** BUILD FAILED **
The nut of the problem is that the "L" in "SQLite" must be capitalized or the build will fail on Macs that have case-sensitive filesystems.
> Fix Carthage build errors on case-sensitive filesystem

- SQLite/Foundation.swift
withouth import Foundation sometimes will cause Compile Error
> Fix no Foundation import error

- SQLite/Typed/Query.swift
- SQLiteTests/QueryTests.swift
> Fix namespacing all of a table's columns using *

- .travis.yml
- SQLite/Core/Statement.swift
- SQLite/Core/Value.swift
- SQLite/Extensions/FTS4.swift
- SQLite/Helpers.swift
- SQLite/Typed/Expression.swift
- SQLite/Typed/Query.swift
- SQLiteTests/TestHelpers.swift
This PR resolves build errors in test target connected with change in declaration of one of XCTest methods (String was replaced with StaticString). It also resolves all warnings about deprecation of ++ operators etc. This PR should be merged after official release of Xcode 7.3.
> Swift22 fixes

- CocoaPods/ios.modulemap
- CocoaPods/osx.modulemap
- CocoaPods/tvos.modulemap
- SQLite.swift.podspec
- SQLite.xcodeproj/project.pbxproj
- podstuff/module.modulemap
This should hopefully fix issues #349 #378 and includes work from #379.
Please test on your platform and report if it works!
``` ruby
pod "SQLite.swift",
git: "https://github.com/stephencelis/SQLite.swift",
branch: "cocoapods-xcode-7-3"
```
Will merge when things look good!
> CocoaPods fix: Xcode 7.3

- CocoaPods/watchos.modulemap
- SQLite.swift.podspec
- SQLite.xcodeproj/project.pbxproj
Replacing and Closing #381 now based against master.
Regarding tests: the existing ones pass, but it seems like there is no test suite for watch os apps. If somebody knows how to add them, I'd be happy to do it, but I just can't find that option.
However I've successfully integrated this version in my watch app which used an older version of SQLite.swift.
Let me know if there's anything else missing, I'd be happy to amend.
> WatchOS support

- SQLite/Typed/Query.swift
- SQLite/Typed/Schema.swift
- SQLiteTests/SchemaTests.swift
- SQLiteTests/TestHelpers.swift
Qualified table names are not allowed when creating indexes or foreign key references.
Fixes #395
> Restrict use of qualified table names

- SQLite.xcodeproj/project.pbxproj
Makes life easier so when we switch into this project Xcode automatically selects the correct tab & indent width.
> Set project tab & indent settings

- Documentation/Index.md
- SQLite.swift.podspec
- SQLite/Core/Connection.swift
- SQLite/Core/Statement.swift
- SQLite/Helpers.swift
Adresses #401.
Not sure about the "standalone" spec name – I just followed the pattern used in https://github.com/ccgus/fmdb/blob/master/FMDB.podspec.
Passes `pod spec lint --allow-warnings`.
The existing behavior and setup is left unchanged. I can't think of a good way to integrate the SQLite sources in a submodule, maybe this could be addressed in a separate PR.
It also needs tests – maybe a dummy project could be set up automatically, including test suite.
> CocoaPods: build standalone version of SQLite with subspec

- Documentation/Index.md
- SQLite.xcodeproj/project.pbxproj
- SQLite/Extensions/FTS4.swift
- SQLite/Extensions/FTS5.swift
- SQLiteTests/FTS4Tests.swift
- SQLiteTests/FTS5Tests.swift
This PR adds support for setting all available parameters for FTS4 with a fluent builder-style interface, #164.
Bonus: Support for [FTS5](https://www.sqlite.org/fts5.html)  which differs in a lot of ways from FTS4 but also shares a few config options.
However most users won't need this bit so it might make sense to compile it in conditionally? OTOH it's not a lot of extra code, and pulling in a FTS5-enabled version of SQLite is fairly straightforward now (with CocoaPods / #431).
> Expose full FTS4/5 configuration

- SQLite/Core/Connection.swift
Really need to use negative primary key in my project.
> Prevent from crash when lastInsertRowId is negative

- SQLite/Core/Connection.swift
- SQLite/Typed/CoreFunctions.swift
Adds two imports that become apparent when not compiling the original project, but adding the files directly.
> Add missing imports

- Makefile
If you look at the logs of any of the previous travis builds, they all run Mac tests, even when the scheme is set to "SQLite iOS". This should fix that.
> Run desired unit tests instead of only Mac.

- SQLite/Typed/Query.swift
- SQLiteTests/QueryTests.swift
I fixed the issue reported in #414 to avoid app crash.
> Throw an error occurred inside Query.pluck()

- README.md
Cocoapods 1.0.1 is now stable so we dont need to pass --pre argument
supersedes #476
> remove --pre argument

- Sources/SQLite/Core/Connection.swift
- Sources/SQLite/Typed/Schema.swift
Looks like some of the docs might have gotten left behind in the great renaming
> Fix usages of old Swift 2 enum case names

- Documentation/Index.md
The old way shown causes a build error in swift 3 (XCode8):
Ambiguous reference to member 'print(_:separator:terminator:)'
> Fix demonstration of how to trace SQL statements in docs

- Documentation/Index.md
- SQLite.xcodeproj/project.pbxproj
- Sources/SQLite/Typed/Coding.swift
- Sources/SQLite/Typed/Query.swift
- Tests/SQLiteTests/QueryTests.swift
- Tests/SQLiteTests/TestHelpers.swift
- Insert or update from an Encodable type
- Decode a row into a Decodable type
Closes stephencelis/SQLite.swift#727
> Add Coding support

- SQLite/Core/Connection.swift
- SQLiteTests/ConnectionTests.swift
This can happen e.g. when using deferred foreign keys (as seen in the tests), or when accessing the database from multiple processes, causing a commit to fail with an "database is busy" error.
> Fix transactions not being rolled back when the individual statements succeed, but the committing the transaction fails.

- Sources/SQLite/Core/Connection.swift
- Sources/SQLite/Typed/Expression.swift
- Sources/SQLite/Typed/Query.swift
- Sources/SQLite/Typed/Schema.swift
- Tests/SQLiteTests/ConnectionTests.swift
Prevents warnings in Xcode 9.1 by adopting proper Swift 4 syntax.
cc @noahsmartin @fdiaz
> Do not use .characters on Strings

- Sources/SQLite/Helpers.swift
Resolved a warning that was caused dude to "characters" deprecation in "String"
> Resolved the warning that was raised because "characters" of a "String" has been deprecated.

- Documentation/Index.md
- corrected method name
- added : instead of =
> Fixed one of Executing Arbitrary SQL examples

- Sources/SQLite/Typed/Coding.swift
Fixed a mistype that prevented building SQLite.swift as non-framework sources.
Steps to reproduce:
- download the source
- create new XCode project
- add SQLite.swift sources inside new project (just sources, not the actual .xcodeproj file)
- build.
As result: sources are built as is and no framework is created -> reference to `SQLite.` becomes invalid. 
Keeping in mind that `Setter` is referenced in this file earlier I assume this is a mistype.
> Fix for non-framework build

- Sources/SQLite/Helpers.swift
- Sources/SQLite/Typed/AggregateFunctions.swift
- Sources/SQLite/Typed/CoreFunctions.swift
- Sources/SQLite/Typed/Operators.swift
resolves #888 
> In Xcode 10.2 beta 4 the macro `#function` shows a different behaviour. As SQLite.swift relies on `#function` in different subroutines for the composition of SQLite queries, several bugs linked to invalid SQLite statements seem to be introduced.
I replaced all the `#function` magic by static strings.
> fix xcode-10.2 issues

- .travis.yml
- Documentation/Index.md
- Makefile
- README.md
- SQLite.swift.podspec
- SQLite.xcodeproj/project.pbxproj
- SQLite.xcodeproj/xcshareddata/xcschemes/SQLite Mac.xcscheme
- SQLite.xcodeproj/xcshareddata/xcschemes/SQLite iOS.xcscheme
- SQLite.xcodeproj/xcshareddata/xcschemes/SQLite tvOS.xcscheme
- SQLite.xcodeproj/xcshareddata/xcschemes/SQLite watchOS.xcscheme
- Sources/SQLite/Foundation.swift
- Sources/SQLite/Info.plist
- Sources/SQLite/Typed/CustomFunctions.swift
- Tests/CocoaPods/Gemfile
- Tests/CocoaPods/Makefile
- Tests/SQLiteTests/FoundationTests.swift
Per recent discussion, this bumps the version to 0.11.6 and updates the project to Swift 5.
First time contributing, so please forgive anything I've missed in this.
One change in Foundation.swift I'm not 100% sure about because it required force unwrapping `pointer.baseAddress` within `withUnsafeBytes`, but I wasn't able to find anything less invasive to the current implementation.
> Version 0.11.6

- .travis.yml
- CONTRIBUTING.md
- Documentation/Index.md
- Makefile
- Package.swift
- README.md
- SQLite.swift.podspec
- SQLite.xcodeproj/project.pbxproj
- Sources/SQLite/Info.plist
- Tests/CocoaPods/Makefile
This updates the project to Swift 5, and also updates the iOS simulator to iPhone XS.
> Version 0.12 (Swift 5)

- .travis.yml
- CHANGELOG.md
- Makefile
- Package.swift
- SQLite.xcodeproj/project.pbxproj
- SQLite.xcodeproj/xcshareddata/xcschemes/SQLite Mac.xcscheme
- SQLite.xcodeproj/xcshareddata/xcschemes/SQLite iOS.xcscheme
- SQLite.xcodeproj/xcshareddata/xcschemes/SQLite tvOS.xcscheme
- SQLite.xcodeproj/xcshareddata/xcschemes/SQLite watchOS.xcscheme
- Sources/SQLiteObjc/SQLiteObjc.h
- Sources/SQLiteObjc/include/README.md
- Tests/Carthage/Makefile
* Updates ruby version used by Travis-CI.
* Updates Xcode image to 12.5 for Travis-CI.
* Removes workaround in run-tests.sh for older simulators.
* Updates Carthage toolchain.
* Updates Package.swift tool version.
* Fixes up SPM build for SQLiteObjc module.
> Updates for Xcode 12.5

- README.md
Because of #988 and #983, I added a do...catch in the usage section, and a production implementation example in the related section.
Fix #988 
Fix #983
> Improving README.md to fix 2 issues

- README.md
Fixes #920 - the issue suggests that Swift 4.2 or below doesn't work in version 0.11.6. This PR adds this version to "requires Swift 5" in the README.
> Update version requirements (Fix #920)

- Sources/SQLite/Typed/Operators.swift
- Tests/SQLiteTests/OperatorsTests.swift
Sometimes, you explicitly want the "IS" operator, unlike the automatic logic that sometimes uses the IS operator when using the == operator with expressions.
Possible solution for feature request stephencelis/SQLite.swift#1003
- Added === as explicit “IS” operator for expressions.
- Added tests for === operator.
> Added === as explicit “IS” operator for expressions

- Sources/SQLite/Extensions/FTS4.swift
- Sources/SQLite/Extensions/FTS5.swift
Hi,
This fixes the compiler warnings when using the FTSConfig* classes without chaining the methods calls.
For example this works fine :
```swift
let config = FTS5Config()
.column(subject)
.column(body, [.unindexed])
.prefix([2, 3])
```
But this emits a warning (but shouldn't because the first version is just syntaxic sugar and the semantics are the same here) :
```swift
let config = FTS5Config()
config.column(subject)
config.column(body, [.unindexed])
config.prefix([2, 3]) // warning: Result of call to 'prefix' is unused
```
This PR adresses this issue by adding `@discardableResult` to all methods of the FTSConfig* classes returning `Self`.
> Add @discardableResult to all FTSConfig methods returning Self for chaining

- Sources/SQLite/Helpers.swift
- Sources/SQLite/Typed/Operators.swift
- Tests/SQLiteTests/OperatorsTests.swift
When you're programmatically building a query to execute, you have times where you build a variable number of clauses by which you filter a table. There isn't a great way to turn an `Array<Expression<Bool>>` into an `Expression<Bool>`, short of making a large `(a AND (b AND (c AND (d AND e))))` expression.
`and` and `or` fix this by allowing you to turn an `Array<Expression<Bool>>` directly into a lower-complexity clause: `(a AND b AND c AND d AND e)`
> Add `and` and `or` functions

- Documentation/Index.md
- Sources/SQLite/Typed/Coding.swift
- Sources/SQLite/Typed/Query.swift
- Sources/SQLite/Typed/Setter.swift
- Tests/SQLiteTests/QueryTests.swift
Apps need the ability to insert or, if the row already exists, update the existing row. This is commonly called "upsert" and is [documented for SQLite here](https://www.sqlite.org/lang_UPSERT.html). The existing "replace" on conflict clause for `insert()` often does not have the desired behavior. It will cascade (with deletes, if specified) along foreign keys if the value exists and has to be replaced ([see Issue 842](https://github.com/stephencelis/SQLite.swift/issues/842)).
Create an `upsert()` method for queries. The basic form allows for the fallback setters to be manually specified. A slightly more ergonomic version will compute the setters from the inserted values by removing the "conflicting" column, and then using the inserted values via the "excluded" qualifier. Additionally, an …
> Implement Upsert [#482]

- Sources/SQLite/Core/Connection.swift
- Tests/SQLiteTests/ConnectionTests.swift
Fixes #1047 
Usage:
```swift
try connection.vacuum()
```
> Adding a `vacuum()` fonction to `Connection`

- Package.swift
- SQLite.xcodeproj/project.pbxproj
- Tests/SPM/Package.swift
1. Adds platform versions to the SPM manifest; we discovered this was missing while debugging https://github.com/apollographql/apollo-ios/pull/2015. This addition should allow SPM to correctly resolve deployment targets.
2. Moves the Xcode deployment versions configuration from each target to the project level. There is some personal preference to this change but I do also believe there is value in being able to set all deployment versions in one place (project) vs. the individual targets where it's easy to miss versions not being the same. I also changed the tvOS target to match Cocoapods, which specifies `9.1`.
_I saw that https://github.com/stephencelis/SQLite.swift/pull/1083 already attempted this but that PR seems dead and the fork has also been deleted. If this one is merged you can …
> Align platform versions in SPM manifest and Xcode project

- Documentation/Index.md
Updated position of closing bracket where `onConflictOf` parameter. In this particular area it was closing `upsert()` and making `onConflictOf` a parameter of `.run()`
> Closing bracket position

- Documentation/Index.md
- Sources/SQLite/Core/Statement.swift
- Tests/SQLiteTests/StatementTests.swift
Added unit-test.
Updated Documentation.
> Add prepareRowIterator method to an extension of Statement.

- SQLite.xcodeproj/project.pbxproj
Hi, the Headers build phase should be before the "Compile Sources" build phase. Fixes #1079.
> Fixed build order

- Sources/SQLite/Typed/Query.swift
For issue #1109 
- Previously this allocated arrays every time it was accessed. It will now only allocate in one of the error cases.
- It also keeps track of the columnName index for both key and value so it doesn't need to look it up twice.
> Improve performance of prefixed column resolution

- Sources/SQLite/Helpers.swift
The `quote` function was showing up in my instruments profile.  The current implementation requires an allocation of a one or more strings at every step of the `reduce`. This version adds one character at a time and relies on the geometric growth of the string itself. I personally think it's a little clearer as well.
I considered adding `reserveCapacity` to the beginning, but that might be a bit of a micro-optimization.
> Improve string quote performance

- Documentation/Index.md
'pathForResource(_:ofType:)' has been renamed to 'path(forResource:ofType:)'
> FIX index.md

- Sources/SQLite/Typed/Query.swift
- Tests/SQLiteTests/Typed/QueryIntegrationTests.swift
In  #1139 I introduced support for the `WITH` clause. My implementation contains a bug: preparing a query containing a `SELECT *` preceded by a `WITH` causes an error to be thrown.
Consider the following statement:
```sql
WITH temp AS ( SELECT id, email from users) SELECT * from temp
```
An error is thrown when preparing this statement because the glob expansion procedure tries to determine the column names for the result by looking up the column names for the query `SELECT * from temp`. This does not work because `temp` is a temporary view defined in the `WITH` clause.
To fix this, I modified the glob expansion procedure to include the `WITH` clause in the query used to look up the result column names.
> Fix incorrect behavior when preparing SELECT * preceded by a WITH

- Sources/SQLite/Core/Connection.swift
- Sources/SQLite/Core/Result.swift
- Tests/SQLiteTests/Core/ConnectionTests.swift
- Tests/SQLiteTests/Core/ResultTests.swift
- Tests/SQLiteTests/Typed/QueryIntegrationTests.swift
This change allows developers to diagnose and debug difficult SQLite issues in a backwards compatible fashion by using `sqlite3_extended_errcode()` to return more detailed "extended error codes". See https://sqlite.org/rescode.html#primary_result_codes_versus_extended_result_codes for more info. There is no current mechanism to enable this.
In particular, at dropbox we have seen `SQLITE_IOERR` quite a bit in production and expect that the extended error code will give us more detailed diagnosis (like `SQLITE_IOERR_VNODE` referenced in https://github.com/stephencelis/SQLite.swift/issues/630 and by apple https://devstreaming-cdn.apple.com/videos/wwdc/2016/242vdhuk4hmwrxnb465/242/242_whats_new_in_core_data.pdf)
> Adds support for returning extended error codes

- Sources/SQLite/Schema/SchemaDefinitions.swift
The [documentation](https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#querying-the-schema) suggests that the index schema information can be queried. That requires the `IndexDefinition` properties to be public.
At the moment, the following code does not work, when used in an project that depends on SQLite.swift:
```swift
let indexes = try schema.indexDefinitions("users")
for index in indexes {
print("\(index.name) columns:\(index.columns))") // <- index.name and index.columns is not visible
}
```
`ObjectDefinition` and `ColumnDefinition` properties are already public, so it seems not to far fetched to change the `IndexDefinition` properties as well?
> Make ithe IndexDefinition properties public

- Sources/SQLite/Schema/SchemaReader.swift
- Tests/SQLiteTests/Schema/SchemaReaderTests.swift
The `PRAGMA` `table_info` that is used to return the column definitions, returns one row for each defined column. The `pk` column contains:
> ... either zero for columns that are not part of the primary key, or the 1-based index of the column within the primary key).
See https://www.sqlite.org/pragma.html#pragma_table_info
Checking whether the `pk` column equals 1 only detects a single primary key and ignores other columns that are part of a composite primary key.
Thanks for taking the time to submit a pull request.
Before submitting, please do the following:
- Run `make lint` to check if there are any format errors (install [swiftlint](https://github.com/realm/SwiftLint#installation) first)
- Run `swift test` to see if the tests pass.
- Write new tests for new functionality.
- Update …
> SchemaReader: return the correct column definition for a composite primary key

- Sources/SQLite/Typed/Coding.swift
Closes #997 by adding support for optional types when decoding a row.
> Add optional support for decoding

- Sources/SQLite/Core/Value.swift
- Sources/SQLite/Helpers.swift
- Sources/SQLite/Typed/Query.swift
- Tests/SQLiteTests/Typed/RowTests.swift
When using custom types, sometimes decoding can fail, say due to changes in the type structure. In this case decoding would fail and the only way to handle it is forcing a crash.
This change allows you to use `try row.get()` instead. Givng you the chance to handle the mismatch.
addresses: #778
> make fromDatatypeValue throw

- Documentation/Index.md
- SQLite.xcodeproj/project.pbxproj
- Sources/SQLite/Typed/AggregateFunctions.swift
- Sources/SQLite/Typed/WindowFunctions.swift
- Tests/SQLiteTests/Typed/QueryIntegrationTests.swift
- Tests/SQLiteTests/Typed/WindowFunctionsTests.swift
Adds window functions to Sqlite.swift,  see https://www.sqlite.org/windowfunctions.html#built_in_window_functions. The `OVER` cause was problematic in the current structure of the code, so for now, only `OVER (ORDER BY {expression})` is supported but that is most of the use cases. The `ORDER BY` used here is not the same as the `func order()` in QueryType and cannot used like this.
- row_number()
- rank()
- dense_rank()
- percent_rank()
- cume_dist()
- ntile(N)
- lag(expr, offset, default)
- lead(expr, offset, default)
- first_value(expr)
- last_value(expr)
- nth_value(expr, N)
> Implements built-in window functions

- Sources/SQLite/Schema/SchemaDefinitions.swift
- Tests/SQLiteTests/Schema/SchemaDefinitionsTests.swift
- Tests/SQLiteTests/Schema/SchemaReaderTests.swift
See https://www.sqlite.org/datatype3.html#determination_of_column_affinity for how SQLite determines column affinity.
Fixes #1215
> Fix column affinity parsing to match how SQLite determines affinity (Fix #1215)

- Sources/SQLite/Typed/Coding.swift
- Tests/SQLiteTests/Typed/QueryIntegrationTests.swift
#1247 describes a bug where decoding a nil value in an optional throws an error when nil is a valid response.
This same bug occurs with arrays or structs encoded to either optional string or data types.
I added a unit test "test_insert_custom_encodable_type" which demonstrates the issue. The current master branch fails when decoding a nil value.
> Fix #1247 support nil case when decoding optionals

- CHANGELOG.md
- Documentation/Index.md
- README.md
- SQLite.swift.podspec
- Tests/SPM/Package.swift
Fixes related to #1237 (missing visionOS on cocoapods)
EDIT: Currently SQLCipher is missing visionOS in its podspec too
> fix: visionos to cocoapods

- SQLite.swift.podspec
- SQLite.xcodeproj/project.pbxproj
- Although the source code has a privacy manifest, it is not being included in the pod dependency. Hence, it is not being downloaded to the client app's pods. I have updated the `podspec` to include it as a resource bundle (this is a standard practice to include resources)
- Update the marketing version to the upcoming release version.
Closes https://github.com/stephencelis/SQLite.swift/issues/1263
> Bugfix: Update `podspec` to include privacy manifest

- Documentation/Upgrading.md
- Sources/SQLite/Typed/Setter.swift
- Tests/SQLiteTests/Core/Connection+AttachTests.swift
- Tests/SQLiteTests/Core/CoreFunctionsTests.swift
- Tests/SQLiteTests/Core/StatementTests.swift
- Tests/SQLiteTests/Extensions/FTS4Tests.swift
- Tests/SQLiteTests/Extensions/FTSIntegrationTests.swift
- Tests/SQLiteTests/Schema/SchemaChangerTests.swift
- Tests/SQLiteTests/Schema/SchemaReaderTests.swift
- Tests/SQLiteTests/TestHelpers.swift
- Tests/SQLiteTests/Typed/CustomFunctionsTests.swift
- Tests/SQLiteTests/Typed/ExpressionTests.swift
- Tests/SQLiteTests/Typed/OperatorsTests.swift
- Tests/SQLiteTests/Typed/QueryIntegrationTests.swift
- Tests/SQLiteTests/Typed/QueryTests.swift
- Tests/SQLiteTests/Typed/RowTests.swift
- Tests/SQLiteTests/Typed/SelectTests.swift
- Tests/SQLiteTests/Typed/SetterTests.swift
- Tests/SQLiteTests/Typed/WindowFunctionsTests.swift
`Setter` has a extension of `Expressible`, but the `asSQL()` is internal, so I implement the `CustomStringConvertible` like the Expressions.
Thanks for taking the time to submit a pull request.
Before submitting, please do the following:
- Run `make lint` to check if there are any format errors (install [swiftlint](https://github.com/realm/SwiftLint#installation) first)
- Run `swift test` to see if the tests pass.
- Write new tests for new functionality.
- Update documentation comments where applicable.
> Fix: Add `CustomStringConvertible` for Setter

- Package.swift
- Sources/SQLite/Core/Backup.swift
- Sources/SQLite/Core/Connection+Aggregation.swift
- Sources/SQLite/Core/Connection+Attach.swift
- Sources/SQLite/Core/Connection.swift
- Sources/SQLite/Core/Result.swift
- Sources/SQLite/Core/Statement.swift
- Sources/SQLite/Helpers.swift
- Tests/SQLiteTests/Core/Connection+AttachTests.swift
- Tests/SQLiteTests/Core/Connection+PragmaTests.swift
- Tests/SQLiteTests/Core/ConnectionTests.swift
- Tests/SQLiteTests/Core/ResultTests.swift
- Tests/SQLiteTests/Core/StatementTests.swift
- Tests/SQLiteTests/Extensions/FTSIntegrationTests.swift
- Tests/SQLiteTests/Typed/CustomAggregationTests.swift
- Tests/SQLiteTests/Typed/QueryIntegrationTests.swift
- Tests/SQLiteTests/Typed/QueryTests.swift
allows SQLite.swift to be used for cross compilation with `swift build --swift-sdk x86_64-swift-linux-musl` command
> fix cross compilation for linux on macOS fails #1317
