- .gitmodules
- SQLite Common/Database.swift
- SQLite Common/SQLite-Bridging.h
- SQLite Mac sqlcipher-Info.plist
- SQLite iOS sqlcipher-Info.plist
- SQLite.playground/section-2.swift
- SQLite.xcodeproj/project.pbxproj
- SQLite.xcodeproj/project.xcworkspace/xcshareddata/SQLite.xccheckout
- SQLite.xcodeproj/xcshareddata/xcschemes/SQLite Mac sqlcipher.xcscheme
- SQLite.xcodeproj/xcshareddata/xcschemes/SQLite iOS sqlcipher.xcscheme
- compile using sqlcipher repository
- add key and rekey functions; rekey(0,0) does not work yet as I could not figure out the right type in swift
> sqlcipher support

- SQLite Tests/SchemaTests.swift
- SQLite Tests/TestHelper.swift
- SQLite/Schema.swift
Opened a version of #76 against master (and swift 1.1). Feel free to merge either
> Support non-integer primary key in shorthand function

- SQLite.swift.podspec
fix the podspec for the swift-2.0 branch
> fix podspec var name

- Source/Extensions/FTS4.swift
- Source/Extensions/R*Tree.swift
- Source/Helpers.swift
- Source/Typed/AggregateFunctions.swift
- Source/Typed/CoreFunctions.swift
- Source/Typed/Expression.swift
- Source/Typed/Query.swift
- Source/Typed/Schema.swift
fixed issues as best I could with current knowledge re: Xcode 7 beta 6 language changes
Converted to Swift 2.0 for XCode 7.0 Beta 6. Compiles but does not pass tests.
> XCode 7.0 Beta 6 Swift 2.0 conversion

- SQLite/Value.swift
> Change Blob internal value from NSData to [UInt8]

- README.md
> Add support links to features, add link to SQLiteCipher, Gitter link

- Makefile
- run-tests.sh
> Makefile: re-add scheme default

- Documentation/Index.md
- README.md
> Update instructions for manual install

- SQLite/Core/Connection.swift
- SQLiteTests/ConnectionTests.swift
As a result of some debugging nightmares in #546
> Better error messages

- Documentation/Index.md
> Make it clear that pod needs to be included once

- .travis.yml
- run-tests.sh
https://blog.travis-ci.com/2017-06-06-xcode-833-is-here
(repeatable builds, it's a thing)
> Travis sneakily replaced the Xcode 8.3 image

- SQLite.xcodeproj/project.pbxproj
> No longer needed

- Documentation/Index.md
> Corected HEIFIamge to HEIFImage

- SQLite.xcodeproj/xcshareddata/xcschemes/SQLite Mac.xcscheme
- SQLite.xcodeproj/xcshareddata/xcschemes/SQLite iOS.xcscheme
- SQLite.xcodeproj/xcshareddata/xcschemes/SQLite tvOS.xcscheme
> Remove codeCoverageEnabled

- Sources/SQLite/Foundation.swift
- Tests/SQLiteTests/FoundationTests.swift
Storing them as string for better readability in the database
> Add support for storing and retrieving UUID objects

- Documentation/Index.md
few things wasnt closed properly
> closing brackets/aposthrophes

- Documentation/Index.md
- Sources/SQLite/Typed/Coding.swift
- Tests/SQLiteTests/QueryTests.swift
- Tests/SQLiteTests/TestHelpers.swift
- Add Date support to Codable
- Following #850 (but with tests)
All tests passed.
> Codable - Add Date support

- Documentation/Index.md
Documentation update for #1019
> Updated documentation for `===` and `!==` operators.

- Sources/SQLite/Typed/Coding.swift
Simple addition to the codable api to pass a onConflict parameter to the insert function.
> Codable insert support onConflict

- Sources/SQLite/Extensions/FTS4.swift
- Tests/SQLiteTests/FTS4Tests.swift
- Tests/SQLiteTests/FTS5Tests.swift
https://www.sqlite.org/fts3.html#tokenizer
Closes #1128
> removeDiacritics => remove_diacritics

- Documentation/Index.md
Small typo fix (iff -> if). Added code comment, then modified existing code comment to make the intent of the code clearer.
Thanks for taking the time to submit a pull request.
Before submitting, please do the following:
- Run `make lint` to check if there are any format errors (install [swiftlint](https://github.com/realm/SwiftLint#installation) first)
- Run `swift test` to see if the tests pass.
- Write new tests for new functionality.
- Update documentation comments where applicable.
> Fixed typo and added/clarified code comment in documentation.

- README.md
A minor fix as per https://github.com/badges/shields/issues/8671
> Fix GitHub Actions build badge

- SQLite.xcodeproj/project.pbxproj
- Sources/SQLite/PrivacyInfo.xcprivacy
Add privacy manifest and fixes a build [issue](https://github.com/stephencelis/SQLite.swift/actions/runs/8019552944/job/21907598856) found on a previous [pull request](https://github.com/stephencelis/SQLite.swift/pull/1234).
> Add privacy manifest

- README.md
> add SQLite. prefix for Expression in README
